### ISSUE TITLE
Fail in Application Mode

### ISSUE THREAD

**Issue by pacomf** [ibm-messaging/iot-python#19]
Hi!

  I'm trying to use version 0.2.2 of the library, but does not work. I think there is a bug in line 229 in application.py, because you iterate the subscriptions like 'subscription', so you should use 'subscription' object, not 'subscriptions' to access to the elements.

  I made the change locally, but other error appear: Now, I can connect, but the device is connected and disconnected constantly. Can you check it?. Meanwhile I will continue using the version 0.1.8. :)

   https://github.com/ibm-messaging/iot-python/blob/master/src/ibmiotf/application.py#L229

   Regards.
   Paco Martín.

**Comment by durera** [comment]
Doh.  Not sure how I missed that one.  Give 0.2.3 a try when I push it out in a minute.  I inserted a disconnect/connect in the simpleApp solution and it sucessfully restored the subscriptions on reconnect.
